-- Phase 47 DIR-14..DIR-17, DIR-22: CSV-import schema upgrade. Order: enum DDL first → TRUNCATE old data → ALTER table → DROP old enum.
-- Doctor table wiped per D-12 (Phase 46 shipped with seed/test data only).
-- Migration sequence: CREATE TYPE Fachrichtung → TRUNCATE Doctor → ALTER TABLE Doctor (add arztNr, profilUrl, fachrichtung enum, drop kategorie, drop fachrichtung text, drop website) → DROP TYPE DoctorKategorie → CREATE indexes.
-- Postgres DROP COLUMN auto-drops dependent indexes (Doctor_kategorie_idx) — no separate DROP INDEX needed.

-- CreateEnum
CREATE TYPE "Fachrichtung" AS ENUM (
  'ALLGEMEINMEDIZIN',
  'ALLGEMEINMEDIZIN_UND_FAMILIENMEDIZIN',
  'INNERE_MEDIZIN',
  'FRAUENHEILKUNDE_UND_GEBURTSHILFE',
  'AUGENHEILKUNDE_UND_OPTOMETRIE',
  'ALLGEMEINCHIRURGIE_UND_VISZERALCHIRURGIE',
  'ORTHOPAEDIE_UND_TRAUMATOLOGIE',
  'UNFALLCHIRURGIE',
  'ORTHOPAEDIE_UND_ORTHOPAEDISCHE_CHIRURGIE',
  'PSYCHIATRIE_U_PSYCHOTHERAPEUTISCHE_MEDIZIN',
  'HAUT_UND_GESCHLECHTSKRANKHEITEN',
  'KINDER_UND_JUGENDHEILKUNDE',
  'HALS_NASEN_UND_OHRENHEILKUNDE',
  'NEUROLOGIE',
  'RADIOLOGIE',
  'UROLOGIE',
  'ANAESTHESIOLOGIE_UND_INTENSIVMEDIZIN',
  'PLASTISCHE_REKONSTRUKTIVE_U_AESTHETISCHE_CHIRURGIE',
  'INNERE_MEDIZIN_UND_KARDIOLOGIE',
  'LUNGENKRANKHEITEN',
  'PSYCHIATRIE_UND_NEUROLOGIE',
  'MUND_KIEFER_UND_GESICHTSCHIRURGIE',
  'NEUROLOGIE_UND_PSYCHIATRIE',
  'NEUROCHIRURGIE',
  'KINDER_U_JUGENDPSYCHIATRIE_U_PSYCHOTHERAPEUTISCHE_MEDIZIN',
  'APPROBIERTER_ARZT',
  'MEDIZINISCHE_UND_CHEMISCHE_LABORDIAGNOSTIK',
  'PHYSIKALISCHE_MEDIZIN_U_ALLGEMEINE_REHABILITATION',
  'PSYCHIATRIE',
  'ALLGEMEINCHIRURGIE_UND_GEFAESSCHIRURGIE',
  'INNERE_MEDIZIN_UND_PNEUMOLOGIE',
  'NUKLEARMEDIZIN',
  'KINDER_UND_JUGENDPSYCHIATRIE',
  'KLINISCHE_PATHOLOGIE_UND_MOLEKULARPATHOLOGIE',
  'KINDER_UND_JUGENDCHIRURGIE',
  'HERZCHIRURGIE',
  'INNERE_MEDIZIN_UND_GASTROENTEROLOGIE_UND_HEPATOLOGIE',
  'KLINISCHE_MIKROBIOLOGIE_UND_HYGIENE',
  'STRAHLENTHERAPIE_RADIOONKOLOGIE',
  'ANATOMIE',
  'KLINISCHE_IMMUNOLOGIE',
  'THORAXCHIRURGIE',
  'ARBEITSMEDIZIN',
  'GERICHTSMEDIZIN',
  'INNERE_MEDIZIN_UND_ANGIOLOGIE',
  'INNERE_MEDIZIN_UND_ENDOKRINOLOGIE_U_DIABETOLOGIE',
  'INNERE_MEDIZIN_UND_HAEMATOLOGIE_UND_INTERNISTISCHE_ONKOLOGIE',
  'INNERE_MEDIZIN_UND_INFEKTIOLOGIE',
  'INNERE_MEDIZIN_UND_INTENSIVMEDIZIN',
  'INNERE_MEDIZIN_UND_NEPHROLOGIE',
  'MEDIZINISCHE_GENETIK'
);

-- Wipe Phase 46 seed/test data — arztNr NOT NULL has no per-row backfill; D-12 authorizes TRUNCATE.
TRUNCATE TABLE "Doctor" RESTART IDENTITY;

-- AlterTable — single statement, all column mutations together.
ALTER TABLE "Doctor"
  DROP COLUMN "kategorie",
  DROP COLUMN "fachrichtung",
  DROP COLUMN "website",
  ADD COLUMN "arztNr"       TEXT             NOT NULL,
  ADD COLUMN "fachrichtung" "Fachrichtung"   NOT NULL,
  ADD COLUMN "profilUrl"    TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Doctor_arztNr_key" ON "Doctor"("arztNr");
CREATE INDEX "Doctor_fachrichtung_idx" ON "Doctor"("fachrichtung");

-- DropEnum — must come AFTER DROP COLUMN (above) which removes the column using this type.
DROP TYPE "DoctorKategorie";
