/**
 * Phase 18 unit tests — Homepage Editorial Layout data layer.
 *
 * Covers: getFeaturedArticle, getPinnedArticles, hasEilmeldung,
 *         listArticlesForHomepage, groupArticlesByBezirk
 */
import { describe, it, expect, beforeAll, beforeEach } from 'vitest'
import { randomUUID } from 'node:crypto'
import type { ArticleStatus, PrismaClient } from '@prisma/client'
import { createTestDb, cleanDb } from './setup-db'
import {
  getFeaturedArticle,
  getPinnedArticles,
  hasEilmeldung,
  listArticlesForHomepage,
  groupArticlesByBezirk,
} from '../lib/content/articles'

let db: PrismaClient

beforeAll(async () => {
  db = await createTestDb()
})

// Helper to create a minimal published article
async function createArticle(
  overrides: Partial<{
    status: ArticleStatus
    isFeatured: boolean
    isPinned: boolean
    isEilmeldung: boolean
    isStateWide: boolean
    imageUrl: string | null
    publishedAt: Date
    title: string
  }> = {}
) {
  return db.article.create({
    data: {
      publicId: randomUUID(),
      source: 'MANUAL',
      status: overrides.status ?? 'PUBLISHED',
      isAutoGenerated: false,
      isFeatured: overrides.isFeatured ?? false,
      isPinned: overrides.isPinned ?? false,
      isEilmeldung: overrides.isEilmeldung ?? false,
      isStateWide: overrides.isStateWide ?? false,
      imageUrl: overrides.imageUrl ?? null,
      title: overrides.title ?? `Test Artikel ${randomUUID()}`,
      publishedAt: overrides.publishedAt ?? new Date(),
    },
  })
}

// Helper to create a bezirk
async function createBezirk(slug: string, name: string) {
  return db.bezirk.upsert({
    where: { slug },
    update: {},
    create: { slug, name, gemeindeSynonyms: [] },
  })
}

// Helper to tag an article to a bezirk
async function tagArticle(articleId: number, bezirkId: number) {
  return db.articleBezirk.create({ data: { articleId, bezirkId } })
}

// ─── getFeaturedArticle ───────────────────────────────────────────────────────

describe('getFeaturedArticle', () => {
  beforeEach(async () => { await cleanDb(db) })

  it('returns the article with isFeatured=true when one exists', async () => {
    const featured = await createArticle({ isFeatured: true, title: 'Featured Artikel' })
    await createArticle({ title: 'Normaler Artikel' })

    const result = await getFeaturedArticle(db)

    expect(result).not.toBeNull()
    expect(result!.id).toBe(featured.id)
    expect(result!.isFeatured).toBe(true)
  })

  it('returns the newest published article when none have isFeatured=true', async () => {
    const older = await createArticle({
      publishedAt: new Date('2026-01-01'),
      title: 'Älterer Artikel',
    })
    const newer = await createArticle({
      publishedAt: new Date('2026-03-01'),
      title: 'Neuerer Artikel',
    })

    const result = await getFeaturedArticle(db)

    expect(result).not.toBeNull()
    expect(result!.id).toBe(newer.id)
    // The older article exists but should not be returned
    expect(result!.id).not.toBe(older.id)
  })

  it('returns null when there are no published articles', async () => {
    await createArticle({ status: 'FETCHED' })

    const result = await getFeaturedArticle(db)

    expect(result).toBeNull()
  })
})

// ─── getPinnedArticles ────────────────────────────────────────────────────────

describe('getPinnedArticles', () => {
  beforeEach(async () => { await cleanDb(db) })

  it('returns pinned published articles', async () => {
    const pinned1 = await createArticle({ isPinned: true, title: 'Gepinnter Artikel 1' })
    const pinned2 = await createArticle({ isPinned: true, title: 'Gepinnter Artikel 2' })
    await createArticle({ title: 'Normaler Artikel' })

    const result = await getPinnedArticles(db)

    expect(result.length).toBe(2)
    const ids = result.map((a) => a.id)
    expect(ids).toContain(pinned1.id)
    expect(ids).toContain(pinned2.id)
  })

  it('filters by bezirkIds and includes isStateWide articles', async () => {
    const bezirk1 = await createBezirk('graz', 'Graz (Stadt)')
    const bezirk2 = await createBezirk('leoben', 'Leoben')

    const pinnedInGraz = await createArticle({ isPinned: true, title: 'Gepinnt in Graz' })
    await tagArticle(pinnedInGraz.id, bezirk1.id)

    const pinnedInLeoben = await createArticle({ isPinned: true, title: 'Gepinnt in Leoben' })
    await tagArticle(pinnedInLeoben.id, bezirk2.id)

    const stateWide = await createArticle({ isPinned: true, isStateWide: true, title: 'Steiermarkweit' })

    // Request only Graz bezirk
    const result = await getPinnedArticles(db, { bezirkIds: [bezirk1.id] })

    const ids = result.map((a) => a.id)
    expect(ids).toContain(pinnedInGraz.id)
    expect(ids).toContain(stateWide.id)
    expect(ids).not.toContain(pinnedInLeoben.id)
  })

  it('falls back to newest published articles when none are pinned', async () => {
    const article1 = await createArticle({ title: 'Artikel 1' })
    const article2 = await createArticle({ title: 'Artikel 2' })

    const result = await getPinnedArticles(db)

    expect(result.length).toBeGreaterThan(0)
    const ids = result.map((a) => a.id)
    expect(ids).toContain(article1.id)
    expect(ids).toContain(article2.id)
  })

  it('respects the limit option', async () => {
    for (let i = 0; i < 5; i++) {
      await createArticle({ isPinned: true, title: `Gepinnt ${i}` })
    }

    const result = await getPinnedArticles(db, { limit: 3 })

    expect(result.length).toBe(3)
  })
})

// ─── hasEilmeldung ────────────────────────────────────────────────────────────

describe('hasEilmeldung', () => {
  beforeEach(async () => { await cleanDb(db) })

  it('returns true when at least one published article has isEilmeldung=true', async () => {
    await createArticle({ isEilmeldung: true, title: 'Eilmeldung!' })

    const result = await hasEilmeldung(db)

    expect(result).toBe(true)
  })

  it('returns false when no articles have isEilmeldung=true', async () => {
    await createArticle({ title: 'Normaler Artikel' })

    const result = await hasEilmeldung(db)

    expect(result).toBe(false)
  })

  it('returns false when isEilmeldung articles are not PUBLISHED', async () => {
    await createArticle({ status: 'FETCHED', isEilmeldung: true, title: 'Unveröffentlicht' })

    const result = await hasEilmeldung(db)

    expect(result).toBe(false)
  })
})

// ─── listArticlesForHomepage ──────────────────────────────────────────────────

describe('listArticlesForHomepage', () => {
  beforeEach(async () => { await cleanDb(db) })

  it('excludes articles with isFeatured=true', async () => {
    const featured = await createArticle({ isFeatured: true, title: 'Featured' })
    const normal = await createArticle({ title: 'Normal' })

    const result = await listArticlesForHomepage(db)

    const ids = result.map((a) => a.id)
    expect(ids).not.toContain(featured.id)
    expect(ids).toContain(normal.id)
  })

  it('orders by isPinned desc then publishedAt desc', async () => {
    const older = await createArticle({ publishedAt: new Date('2026-01-01'), title: 'Älterer' })
    const newer = await createArticle({ publishedAt: new Date('2026-03-01'), title: 'Neuerer' })
    const pinned = await createArticle({ isPinned: true, publishedAt: new Date('2026-01-15'), title: 'Gepinnt' })

    const result = await listArticlesForHomepage(db)

    expect(result[0].id).toBe(pinned.id)      // pinned first
    expect(result[1].id).toBe(newer.id)        // then newest
    expect(result[2].id).toBe(older.id)        // then older
  })

  it('respects the limit option', async () => {
    for (let i = 0; i < 10; i++) {
      await createArticle({ title: `Artikel ${i}` })
    }

    const result = await listArticlesForHomepage(db, { limit: 5 })

    expect(result.length).toBe(5)
  })
})

// ─── groupArticlesByBezirk ────────────────────────────────────────────────────

describe('groupArticlesByBezirk', () => {
  it('groups articles by their first bezirk slug', async () => {
    const bezirk1 = { id: 1, slug: 'graz', name: 'Graz (Stadt)', gemeindeSynonyms: [], createdAt: new Date() }
    const bezirk2 = { id: 2, slug: 'leoben', name: 'Leoben', gemeindeSynonyms: [], createdAt: new Date() }

    const makeArticle = (id: number, bezirke: typeof bezirk1[], stateWide = false) => ({
      id,
      publicId: randomUUID(),
      source: 'MANUAL' as const,
      sourceId: null,
      externalId: null,
      status: 'PUBLISHED' as const,
      isStateWide: stateWide,
      isAutoGenerated: false,
      isFeatured: false,
      isPinned: false,
      isEilmeldung: false,
      imageUrl: null,
      imageCredit: null,
      title: `Artikel ${id}`,
      metaDescription: null,
      seoTitle: null,
      content: null,
      contentHash: null,
      rawPayload: null,
      publishedAt: new Date(),
      retryCount: 0,
      errorMessage: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      bezirke: bezirke.map((b) => ({ bezirk: b, articleId: id, bezirkId: b.id, taggedAt: new Date() })),
    })

    const article1 = makeArticle(1, [bezirk1])
    const article2 = makeArticle(2, [bezirk2])
    const article3 = makeArticle(3, [bezirk1])

    const result = groupArticlesByBezirk([article1, article2, article3])

    expect(result.size).toBe(2)
    expect(result.get('graz')?.articles.length).toBe(2)
    expect(result.get('leoben')?.articles.length).toBe(1)
    expect(result.get('graz')?.name).toBe('Graz (Stadt)')
  })

  it('includes isStateWide articles in all groups', async () => {
    const bezirk1 = { id: 1, slug: 'graz', name: 'Graz (Stadt)', gemeindeSynonyms: [], createdAt: new Date() }
    const bezirk2 = { id: 2, slug: 'leoben', name: 'Leoben', gemeindeSynonyms: [], createdAt: new Date() }

    const makeArticle = (id: number, bezirke: typeof bezirk1[], stateWide = false) => ({
      id,
      publicId: randomUUID(),
      source: 'MANUAL' as const,
      sourceId: null,
      externalId: null,
      status: 'PUBLISHED' as const,
      isStateWide: stateWide,
      isAutoGenerated: false,
      isFeatured: false,
      isPinned: false,
      isEilmeldung: false,
      imageUrl: null,
      imageCredit: null,
      title: `Artikel ${id}`,
      metaDescription: null,
      seoTitle: null,
      content: null,
      contentHash: null,
      rawPayload: null,
      publishedAt: new Date(),
      retryCount: 0,
      errorMessage: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      bezirke: bezirke.map((b) => ({ bezirk: b, articleId: id, bezirkId: b.id, taggedAt: new Date() })),
    })

    const grazArticle = makeArticle(1, [bezirk1])
    const leobenArticle = makeArticle(2, [bezirk2])
    // StateWide article has no bezirk tagging but isStateWide flag
    const stateWideArticle = makeArticle(3, [bezirk1], true) // first bezirk is graz but stateWide

    const result = groupArticlesByBezirk([grazArticle, leobenArticle, stateWideArticle])

    // stateWide should appear in both groups
    const grazIds = result.get('graz')?.articles.map((a) => a.id)
    const leobenIds = result.get('leoben')?.articles.map((a) => a.id)
    expect(grazIds).toContain(stateWideArticle.id)
    expect(leobenIds).toContain(stateWideArticle.id)
  })

  it('excludes articles with no bezirke', async () => {
    const makeArticle = (id: number, hasBezirke: boolean) => ({
      id,
      publicId: randomUUID(),
      source: 'MANUAL' as const,
      sourceId: null,
      externalId: null,
      status: 'PUBLISHED' as const,
      isStateWide: false,
      isAutoGenerated: false,
      isFeatured: false,
      isPinned: false,
      isEilmeldung: false,
      imageUrl: null,
      imageCredit: null,
      title: `Artikel ${id}`,
      metaDescription: null,
      seoTitle: null,
      content: null,
      contentHash: null,
      rawPayload: null,
      publishedAt: new Date(),
      retryCount: 0,
      errorMessage: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      bezirke: hasBezirke
        ? [{ bezirk: { id: 1, slug: 'graz', name: 'Graz (Stadt)', gemeindeSynonyms: [], createdAt: new Date() }, articleId: id, bezirkId: 1, taggedAt: new Date() }]
        : [],
    })

    const withBezirk = makeArticle(1, true)
    const withoutBezirk = makeArticle(2, false)

    const result = groupArticlesByBezirk([withBezirk, withoutBezirk])

    expect(result.size).toBe(1)
    const grazArticleIds = result.get('graz')?.articles.map((a) => a.id)
    expect(grazArticleIds).toContain(withBezirk.id)
    expect(grazArticleIds).not.toContain(withoutBezirk.id)
  })

  it('returns an empty map for empty input', () => {
    const result = groupArticlesByBezirk([])
    expect(result.size).toBe(0)
  })
})
