/**
 * Shared pgLite + Prisma test utility
 *
 * Provides createTestDb() for creating an in-process PostgreSQL instance
 * and cleanDb() for truncating all tables between tests.
 *
 * No Docker required — pgLite compiles PostgreSQL to WebAssembly and runs in-process.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { PGlite } from '@electric-sql/pglite'
import { PrismaPGlite } from 'pglite-prisma-adapter'
import { PrismaClient } from '@prisma/client'

const MIGRATIONS_DIR = join(process.cwd(), 'prisma', 'migrations')

/**
 * Read the initial migration SQL from disk.
 * Returns all migration SQL files concatenated in directory-sorted order.
 */
function loadMigrationSql(): string {
  const { readdirSync } = require('node:fs')
  const migrationDirs = readdirSync(MIGRATIONS_DIR)
    .filter((entry: string) => !entry.includes('.toml'))
    .sort()

  const sqlParts: string[] = []
  for (const dir of migrationDirs) {
    const sqlPath = join(MIGRATIONS_DIR, dir, 'migration.sql')
    try {
      sqlParts.push(readFileSync(sqlPath, 'utf-8'))
    } catch {
      // skip missing files
    }
  }
  return sqlParts.join('\n')
}

/**
 * Creates an in-process pgLite PostgreSQL instance with the full schema applied.
 * Returns a PrismaClient connected through the pgLite adapter.
 *
 * Each call creates a fresh, isolated database — safe for parallel tests.
 */
export async function createTestDb(): Promise<PrismaClient> {
  // Create in-memory pgLite instance (memory:// = no files on disk)
  const pglite = new PGlite()

  // Apply all migrations directly to the in-process database
  const migrationSql = loadMigrationSql()
  await pglite.exec(migrationSql)

  // Connect Prisma through the pgLite adapter
  const adapter = new PrismaPGlite(pglite)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const prisma = new PrismaClient({ adapter } as any)

  return prisma
}

const BEZIRKE = [
  { slug: 'graz', name: 'Graz (Stadt)', gemeindeSynonyms: ['Graz', 'Landeshauptstadt', 'Graz-Stadt', 'LH-Graz'] },
  { slug: 'graz-umgebung', name: 'Graz-Umgebung', gemeindeSynonyms: ['Graz-Umgebung', 'Seiersberg', 'Kalsdorf', 'Grambach', 'Lieboch'] },
  { slug: 'deutschlandsberg', name: 'Deutschlandsberg', gemeindeSynonyms: ['Deutschlandsberg', 'Stainz', 'Schwanberg', 'Wies'] },
  { slug: 'hartberg-fuerstenfeld', name: 'Hartberg-Fürstenfeld', gemeindeSynonyms: ['Hartberg', 'Fürstenfeld', 'Bad Waltersdorf', 'Kaindorf'] },
  { slug: 'leibnitz', name: 'Leibnitz', gemeindeSynonyms: ['Leibnitz', 'Gamlitz', 'Ehrenhausen', 'Leutschach', 'Straß in Steiermark'] },
  { slug: 'leoben', name: 'Leoben', gemeindeSynonyms: ['Leoben', 'Eisenerz', 'Niklasdorf', 'Trofaiach', 'Donawitz'] },
  { slug: 'liezen', name: 'Liezen', gemeindeSynonyms: ['Liezen', 'Ennstal', 'Schladming', 'Bad Aussee', 'Admont', 'Rottenmann', 'Gröbming', 'Irdning', 'Stainach'] },
  { slug: 'murau', name: 'Murau', gemeindeSynonyms: ['Murau', 'Oberwölz', 'Scheifling', 'Stolzalpe'] },
  { slug: 'murtal', name: 'Murtal', gemeindeSynonyms: ['Murtal', 'Judenburg', 'Knittelfeld', 'Zeltweg', 'Fohnsdorf'] },
  { slug: 'bruck-muerzzuschlag', name: 'Bruck-Mürzzuschlag', gemeindeSynonyms: ['Bruck an der Mur', 'Mürzzuschlag', 'Kapfenberg', 'Kindberg', 'Krieglach'] },
  { slug: 'suedoststeiermark', name: 'Südoststeiermark', gemeindeSynonyms: ['Feldbach', 'Bad Gleichenberg', 'Fehring', 'Riegersburg', 'Straden'] },
  { slug: 'voitsberg', name: 'Voitsberg', gemeindeSynonyms: ['Voitsberg', 'Köflach', 'Bärnbach', 'Söding', 'Maria Lankowitz'] },
  { slug: 'weiz', name: 'Weiz', gemeindeSynonyms: ['Weiz', 'Gleisdorf', 'Anger', 'Birkfeld', 'Passail'] },
]

/**
 * Seeds 1000 PUBLISHED articles with publicId and ArticleBezirk associations for performance tests.
 * Upserts all 13 Steiermark Bezirke first, then creates articles in round-robin Bezirk assignment.
 * Call in beforeAll (not beforeEach) — seeding 1000 rows per test would time out.
 */
export async function seedBulkArticles(prisma: PrismaClient, count: number): Promise<void> {
  for (const b of BEZIRKE) {
    await prisma.bezirk.upsert({
      where: { slug: b.slug },
      update: {},
      create: b,
    })
  }

  const bezirke = await prisma.bezirk.findMany()

  for (let n = 0; n < count; n++) {
    const article = await prisma.article.create({
      data: {
        publicId: randomUUID(),
        source: 'MANUAL',
        title: `Artikel ${n}`,
        content: `Inhalt für Artikel ${n}`,
        status: 'PUBLISHED',
        publishedAt: new Date(),
        isAutoGenerated: false,
      },
    })
    await prisma.articleBezirk.create({
      data: { articleId: article.id, bezirkId: bezirke[n % bezirke.length].id },
    })
  }
}

/**
 * Truncates all tables in the test database.
 * Call in beforeEach to ensure a clean state between tests.
 */
export async function cleanDb(prisma: PrismaClient): Promise<void> {
  // Delete in dependency order (child tables first)
  await prisma.pipelineRun.deleteMany()
  await prisma.ingestionRun.deleteMany()
  await prisma.aiSourceConfig.deleteMany()
  await prisma.articleBezirk.deleteMany()
  await prisma.article.deleteMany()
  await prisma.bezirk.deleteMany()
  await prisma.aiConfig.deleteMany()
  await prisma.pipelineConfig.deleteMany()
  await prisma.source.deleteMany()
}
