import { describe, it, expect } from 'vitest'
import { buildArticleMetadata } from './metadata'
import type { ArticleWithBezirke } from '../content/articles'

// Minimal ArticleWithBezirke factory for metadata tests
function makeArticle(overrides: Partial<ArticleWithBezirke> = {}): ArticleWithBezirke {
  return {
    id: 1,
    publicId: 'k7x9mn',
    title: 'Regular Titel',
    seoTitle: 'SEO Titel',
    content: 'Inhalt des Artikels',
    metaDescription: 'Beschreibung',
    status: 'PUBLISHED',
    source: 'OTS_AT',
    externalId: null,
    contentHash: null,
    isAutoGenerated: false,
    isFeatured: false,
    isPinned: false,
    isStateWide: false,
    publishedAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-15T10:00:00Z'),
    createdAt: new Date('2024-01-15T10:00:00Z'),
    pipelineRunId: null,
    reviewNote: null,
    retryCount: 0,
    bezirke: [],
    ...overrides,
  } as unknown as ArticleWithBezirke
}

describe('buildArticleMetadata', () => {
  it('uses seoTitle as og:title when present', () => {
    const article = makeArticle({ seoTitle: 'SEO Titel', title: 'Regular Titel' })
    const result = buildArticleMetadata(article, 'https://example.com')
    expect(result.title).toBe('SEO Titel')
    expect((result.openGraph as { title?: string })?.title).toBe('SEO Titel')
  })

  it('falls back to title when seoTitle is null', () => {
    const article = makeArticle({ seoTitle: null, title: 'Regular Titel' })
    const result = buildArticleMetadata(article, 'https://example.com')
    expect(result.title).toBe('Regular Titel')
  })

  it('uses metaDescription as og:description when present', () => {
    const article = makeArticle({ metaDescription: 'Beschreibung' })
    const result = buildArticleMetadata(article, 'https://example.com')
    expect(result.description).toBe('Beschreibung')
  })

  it('canonical URL uses /artikel/[publicId]/[slug] form based on title', () => {
    const article = makeArticle({ publicId: 'k7x9mn', title: 'Regular Titel', seoTitle: 'SEO Titel' })
    const result = buildArticleMetadata(article, 'https://example.com')
    expect(result.alternates?.canonical).toContain('/artikel/k7x9mn/regular-titel')
  })

  it('og:type is "article"', () => {
    const article = makeArticle()
    const result = buildArticleMetadata(article, 'https://example.com')
    expect((result.openGraph as { type?: string })?.type).toBe('article')
  })

  it('returns empty object when article not found', () => {
    const result = buildArticleMetadata(null, 'https://example.com')
    expect(result).toEqual({})
  })
})
