import { describe, it, expect } from 'vitest'
import type { ArticleWithBezirke } from '@/lib/content/articles'
import { generateBezirkRssFeed } from './rss'

// Minimal ArticleWithBezirke fixture matching the type shape
function makeArticle(overrides: Partial<ArticleWithBezirke> = {}): ArticleWithBezirke {
  return {
    id: 1,
    publicId: 'abc123',
    title: 'Test Artikel',
    seoTitle: 'Test SEO Titel',
    content: '<p>Full article content goes here.</p>',
    metaDescription: 'Description',
    status: 'PUBLISHED',
    source: 'OTS_AT',
    externalId: 'ext-1',
    contentHash: null,
    isAutoGenerated: false,
    isStateWide: false,
    isPinned: false,
    isFeatured: false,
    publishedAt: new Date('2024-01-15T10:00:00Z'),
    createdAt: new Date('2024-01-15T09:00:00Z'),
    updatedAt: new Date('2024-01-15T10:00:00Z'),
    retryCount: 0,
    rawPayload: null,
    bezirke: [],
    ...overrides,
  } as ArticleWithBezirke
}

describe('generateBezirkRssFeed', () => {
  it('returns valid RSS XML string with correct content-type shape', () => {
    const articles = [makeArticle()]
    const xml = generateBezirkRssFeed(articles, 'liezen', 'https://example.at')
    expect(typeof xml).toBe('string')
    // Should be valid RSS XML starting with XML declaration or <rss tag
    expect(xml.trimStart()).toMatch(/^<\?xml|^<rss/)
    expect(xml).toContain('<rss')
    expect(xml).toContain('</rss>')
  })

  it('each item link is the canonical /artikel/[publicId]/[slug] URL', () => {
    const article = makeArticle({ publicId: 'k7x9mn', seoTitle: 'Liezen Unwetter Warnung' })
    const xml = generateBezirkRssFeed([article], 'liezen', 'https://example.at')
    expect(xml).toContain('https://example.at/artikel/k7x9mn/liezen-unwetter-warnung')
  })

  it('includes full article content in description field (not excerpt)', () => {
    const article = makeArticle({ content: '<p>Full article content goes here with many details.</p>' })
    const xml = generateBezirkRssFeed([article], 'liezen', 'https://example.at')
    expect(xml).toContain('Full article content goes here with many details.')
  })

  it('limits to 20 most recent published articles', () => {
    const articles = Array.from({ length: 20 }, (_, i) =>
      makeArticle({ id: i + 1, publicId: `pub${i}`, title: `Artikel ${i}` })
    )
    const xml = generateBezirkRssFeed(articles, 'liezen', 'https://example.at')
    // Count <item> tags
    const itemMatches = xml.match(/<item>/g) ?? []
    expect(itemMatches).toHaveLength(20)
  })

  it('channel title contains the slug name', () => {
    const articles = [makeArticle()]
    const xml = generateBezirkRssFeed(articles, 'liezen', 'https://example.at')
    expect(xml.toLowerCase()).toContain('liezen')
  })

  it('article publicId appears in the guid value', () => {
    const article = makeArticle({ publicId: 'unique-pub-id-xyz' })
    const xml = generateBezirkRssFeed([article], 'steiermark', 'https://example.at')
    expect(xml).toContain('unique-pub-id-xyz')
  })
})
