import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock DAL modules before importing the sitemap function.
// Paths must match the exact import path used in sitemap.ts (relative from app/).
vi.mock('../../lib/content/articles', () => ({
  listArticles: vi.fn(),
}))
vi.mock('../../lib/content/bezirke', () => ({
  listBezirke: vi.fn(),
}))

import { listArticles } from '../../lib/content/articles'
import { listBezirke } from '../../lib/content/bezirke'
import sitemap from '../../app/sitemap'

const mockListArticles = vi.mocked(listArticles)
const mockListBezirke = vi.mocked(listBezirke)

// Minimal bezirk fixture
function makeBezirk(slug: string, name: string, id: number) {
  return { id, slug, name, gemeindeSynonyms: [], createdAt: new Date('2024-01-01') }
}

// Minimal article fixture
function makeArticle(publicId: string, title: string) {
  return {
    id: 1,
    publicId,
    title,
    seoTitle: null,
    content: '<p>content</p>',
    metaDescription: null,
    status: 'PUBLISHED' as const,
    source: 'OTS_AT' as const,
    externalId: 'ext-1',
    contentHash: null,
    isAutoGenerated: false,
    isStateWide: false,
    isPinned: false,
    isFeatured: false,
    publishedAt: new Date('2024-06-15T12:00:00Z'),
    createdAt: new Date('2024-06-15T10:00:00Z'),
    updatedAt: new Date('2024-06-15T12:00:00Z'),
    retryCount: 0,
    rawPayload: null,
    bezirke: [],
  }
}

// 13 Bezirke slugs for Steiermark
const THIRTEEN_BEZIRKE = [
  'bruck-murzzuschlag', 'deutschlandsberg', 'graz', 'graz-umgebung',
  'hartberg-fuerstenfeld', 'judenburg', 'leibnitz', 'leoben',
  'liezen', 'murau', 'murtal', 'suedoststeiermark', 'voitsberg',
].map((slug, i) => makeBezirk(slug, slug, i + 1))

beforeEach(() => {
  vi.clearAllMocks()
})

describe('sitemap', () => {
  it('includes homepage URL with priority 1.0', async () => {
    mockListArticles.mockResolvedValue([])
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://wurzelwelt.at'
    const home = entries.find(e => e.url === base || e.url === `${base}/`)
    expect(home).toBeDefined()
    expect(home?.priority).toBe(1.0)
  })

  it('includes /impressum URL', async () => {
    mockListArticles.mockResolvedValue([])
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://wurzelwelt.at'
    const impressum = entries.find(e => e.url === `${base}/impressum`)
    expect(impressum).toBeDefined()
  })

  it('includes /bezirk/[slug] URLs for all 13 Bezirke', async () => {
    mockListArticles.mockResolvedValue([])
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://wurzelwelt.at'
    const liezene = entries.find(e => e.url === `${base}/bezirk/liezen`)
    expect(liezene).toBeDefined()
    // Count bezirk entries
    const bezirkEntries = entries.filter(e => e.url.includes('/bezirk/'))
    expect(bezirkEntries).toHaveLength(13)
  })

  it('includes /artikel/[publicId]/[slug] URLs for published articles', async () => {
    const article = makeArticle('k7x9mn', 'Liezen Unwetter Warnung')
    mockListArticles.mockResolvedValue([article as any])
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://wurzelwelt.at'
    const articleEntry = entries.find(e => e.url.includes('/artikel/k7x9mn/'))
    expect(articleEntry).toBeDefined()
    expect(articleEntry?.url).toBe(`${base}/artikel/k7x9mn/liezen-unwetter-warnung`)
  })

  it('article URLs use lastModified from publishedAt', async () => {
    const publishedAt = new Date('2024-06-15T12:00:00Z')
    const article = makeArticle('abc111', 'Test Artikel')
    mockListArticles.mockResolvedValue([article as any])
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    const articleEntry = entries.find(e => e.url.includes('/artikel/abc111/'))
    expect(articleEntry).toBeDefined()
    expect(articleEntry?.lastModified).toEqual(publishedAt)
  })

  it('total URL count equals 1 (home) + 1 (impressum) + 13 (bezirke) + N (articles)', async () => {
    const articles = [makeArticle('id1', 'Artikel 1'), makeArticle('id2', 'Artikel 2')]
    mockListArticles.mockResolvedValue(articles as any)
    mockListBezirke.mockResolvedValue(THIRTEEN_BEZIRKE)

    const entries = await sitemap()
    // 1 home + 1 impressum + 13 bezirke + 2 articles = 17
    expect(entries).toHaveLength(17)
  })
})
