-- CreateEnum
CREATE TYPE "ArticleStatus" AS ENUM ('FETCHED', 'TAGGED', 'WRITTEN', 'REVIEW', 'PUBLISHED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ArticleSource" AS ENUM ('OTS_AT', 'RSS', 'MANUAL');

-- CreateTable
CREATE TABLE "Bezirk" (
    "id" SERIAL NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "gemeindeSynonyms" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Bezirk_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Article" (
    "id" SERIAL NOT NULL,
    "externalId" TEXT,
    "source" "ArticleSource" NOT NULL,
    "status" "ArticleStatus" NOT NULL DEFAULT 'FETCHED',
    "isStateWide" BOOLEAN NOT NULL DEFAULT false,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "title" TEXT,
    "metaDescription" TEXT,
    "content" TEXT,
    "rawPayload" JSONB,
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ArticleBezirk" (
    "articleId" INTEGER NOT NULL,
    "bezirkId" INTEGER NOT NULL,
    "taggedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ArticleBezirk_pkey" PRIMARY KEY ("articleId","bezirkId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Bezirk_slug_key" ON "Bezirk"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Bezirk_name_key" ON "Bezirk"("name");

-- CreateIndex
CREATE INDEX "Bezirk_slug_idx" ON "Bezirk"("slug");

-- CreateIndex
CREATE INDEX "Article_status_idx" ON "Article"("status");

-- CreateIndex
CREATE INDEX "Article_publishedAt_idx" ON "Article"("publishedAt");

-- CreateIndex
CREATE INDEX "Article_source_externalId_idx" ON "Article"("source", "externalId");

-- CreateIndex
CREATE INDEX "ArticleBezirk_bezirkId_idx" ON "ArticleBezirk"("bezirkId");

-- AddForeignKey
ALTER TABLE "ArticleBezirk" ADD CONSTRAINT "ArticleBezirk_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ArticleBezirk" ADD CONSTRAINT "ArticleBezirk_bezirkId_fkey" FOREIGN KEY ("bezirkId") REFERENCES "Bezirk"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
