/**
 * Articles Server Actions — CMS-01 and CMS-02
 *
 * Exports pure DB-layer functions (*Db) for testability (injectable PrismaClient).
 * Server Action wrappers (with 'use server' and requireAuth()) delegate to them.
 */
'use server'

import type {
  Article,
  ArticleSource,
  ArticleStatus,
  PrismaClient,
} from '@prisma/client'
import { prisma as defaultPrisma } from '../prisma'
import { ArticleWithBezirke } from '../content/articles'
import { requireAuth } from './auth-node'

// ─── Input types ─────────────────────────────────────────────────────────────

export interface CreateManualArticleInput {
  title: string
  content: string
  bezirkIds: number[]
  seoTitle?: string
  metaDescription?: string
  isPinned?: boolean
  isFeatured?: boolean
}

export interface UpdateArticleInput {
  id: number
  title?: string
  content?: string
  seoTitle?: string
  metaDescription?: string
  bezirkIds?: number[]
}

export interface ListArticlesAdminOptions {
  bezirkId?: number
  sourceType?: ArticleSource
  status?: ArticleStatus | ArticleStatus[]
  fromDate?: Date
  toDate?: Date
  limit?: number
  offset?: number
}

// ─── DB-layer functions (pure, injectable, no auth) ──────────────────────────

/**
 * CMS-01: Create a manual article with Bezirk assignments.
 * source=MANUAL, isAutoGenerated=false, status=PUBLISHED
 */
export async function createManualArticleDb(
  db: PrismaClient,
  input: CreateManualArticleInput
): Promise<Article> {
  const { title, content, bezirkIds, seoTitle, metaDescription, isPinned = false, isFeatured = false } = input

  return db.article.create({
    data: {
      title,
      content,
      seoTitle,
      metaDescription,
      source: 'MANUAL',
      isAutoGenerated: false,
      status: 'PUBLISHED',
      publishedAt: new Date(),
      isPinned,
      isFeatured,
      bezirke: {
        create: bezirkIds.map((bezirkId) => ({ bezirkId })),
      },
    },
  })
}

/**
 * CMS-02: Update article fields. If bezirkIds provided, atomically replaces
 * all ArticleBezirk rows (deleteMany + createMany).
 */
export async function updateArticleDb(
  db: PrismaClient,
  input: UpdateArticleInput
): Promise<Article> {
  const { id, bezirkIds, ...fields } = input

  if (bezirkIds !== undefined) {
    // Atomic Bezirk replacement
    await db.articleBezirk.deleteMany({ where: { articleId: id } })
    await db.articleBezirk.createMany({
      data: bezirkIds.map((bezirkId) => ({ articleId: id, bezirkId })),
    })
  }

  return db.article.update({
    where: { id },
    data: fields,
  })
}

/**
 * CMS-02: Toggle isPinned on the given article.
 */
export async function togglePinDb(
  db: PrismaClient,
  articleId: number
): Promise<Article> {
  const current = await db.article.findUniqueOrThrow({ where: { id: articleId } })
  return db.article.update({
    where: { id: articleId },
    data: { isPinned: !current.isPinned },
  })
}

/**
 * CMS-02: Toggle isFeatured on the given article.
 */
export async function toggleFeatureDb(
  db: PrismaClient,
  articleId: number
): Promise<Article> {
  const current = await db.article.findUniqueOrThrow({ where: { id: articleId } })
  return db.article.update({
    where: { id: articleId },
    data: { isFeatured: !current.isFeatured },
  })
}

/**
 * CMS-02: Soft-delete by setting status=REJECTED.
 */
export async function softDeleteDb(
  db: PrismaClient,
  articleId: number
): Promise<Article> {
  return db.article.update({
    where: { id: articleId },
    data: { status: 'REJECTED' },
  })
}

/**
 * CMS-01/02: List articles with optional filters.
 * Default: excludes REJECTED and FAILED.
 * Returns articles with bezirke relation included.
 */
export async function listArticlesAdmin(
  db: PrismaClient,
  options?: ListArticlesAdminOptions
): Promise<ArticleWithBezirke[]>
export async function listArticlesAdmin(
  options?: ListArticlesAdminOptions
): Promise<ArticleWithBezirke[]>
export async function listArticlesAdmin(
  dbOrOptions?: PrismaClient | ListArticlesAdminOptions,
  options?: ListArticlesAdminOptions
): Promise<ArticleWithBezirke[]> {
  let client: PrismaClient
  let opts: ListArticlesAdminOptions

  if (dbOrOptions !== null && typeof dbOrOptions === 'object' && '$connect' in dbOrOptions) {
    client = dbOrOptions as PrismaClient
    opts = options ?? {}
  } else {
    client = defaultPrisma
    opts = (dbOrOptions as ListArticlesAdminOptions) ?? {}
  }

  const {
    bezirkId,
    sourceType,
    status,
    fromDate,
    toDate,
    limit = 50,
    offset = 0,
  } = opts

  // Default: exclude REJECTED and FAILED unless explicitly requested
  let statusFilter: ArticleStatus | { in: ArticleStatus[] } | { notIn: ArticleStatus[] }
  if (status !== undefined) {
    statusFilter = Array.isArray(status) ? { in: status } : status
  } else {
    statusFilter = { notIn: ['REJECTED', 'FAILED'] as ArticleStatus[] }
  }

  return client.article.findMany({
    where: {
      ...(bezirkId !== undefined ? { bezirke: { some: { bezirkId } } } : {}),
      ...(sourceType !== undefined ? { source: sourceType } : {}),
      status: statusFilter,
      ...(fromDate !== undefined ? { publishedAt: { gte: fromDate } } : {}),
      ...(toDate !== undefined ? { publishedAt: { lte: toDate } } : {}),
    },
    include: {
      bezirke: {
        include: { bezirk: true },
      },
    },
    orderBy: [{ publishedAt: 'desc' }, { createdAt: 'desc' }],
    take: limit,
    skip: offset,
  })
}

// ─── Server Action wrappers (auth-gated, for Next.js Server Actions) ──────────
// These call requireAuth() from next/headers, then delegate to the *Db functions.
// Not called directly in tests — test the *Db functions above instead.

// NOTE: requireAuth() is a placeholder for the auth module (Phase 6).
// For now, Server Actions are exported but auth is not enforced.

export async function createManualArticle(
  input: CreateManualArticleInput
): Promise<Article> {
  await requireAuth()
  return createManualArticleDb(defaultPrisma, input)
}

export async function updateArticle(input: UpdateArticleInput): Promise<Article> {
  await requireAuth()
  return updateArticleDb(defaultPrisma, input)
}

export async function togglePin(articleId: number): Promise<Article> {
  await requireAuth()
  return togglePinDb(defaultPrisma, articleId)
}

export async function toggleFeature(articleId: number): Promise<Article> {
  await requireAuth()
  return toggleFeatureDb(defaultPrisma, articleId)
}

export async function softDelete(articleId: number): Promise<Article> {
  await requireAuth()
  return softDeleteDb(defaultPrisma, articleId)
}

// ─── FormData-based wrappers for use in <form action={...}> ──────────────────
// Next.js Server Actions used in forms receive FormData — these wrappers parse
// the hidden `id` field and delegate to the typed *Db functions.

export async function togglePinForm(formData: FormData): Promise<void> {
  await requireAuth()
  const id = Number(formData.get('id'))
  await togglePinDb(defaultPrisma, id)
}

export async function toggleFeatureForm(formData: FormData): Promise<void> {
  await requireAuth()
  const id = Number(formData.get('id'))
  await toggleFeatureDb(defaultPrisma, id)
}

export async function softDeleteForm(formData: FormData): Promise<void> {
  await requireAuth()
  const id = Number(formData.get('id'))
  await softDeleteDb(defaultPrisma, id)
}

export async function createManualArticleForm(formData: FormData): Promise<void> {
  await requireAuth()
  const { redirect } = await import('next/navigation')
  const bezirkIdsRaw = formData.getAll('bezirkIds').map(Number).filter(Boolean)
  await createManualArticleDb(defaultPrisma, {
    title: formData.get('title')?.toString() ?? '',
    content: formData.get('content')?.toString() ?? '',
    bezirkIds: bezirkIdsRaw,
    seoTitle: formData.get('seoTitle')?.toString() || undefined,
    metaDescription: formData.get('metaDescription')?.toString() || undefined,
    isPinned: formData.get('isPinned') === 'on',
    isFeatured: formData.get('isFeatured') === 'on',
  })
  redirect('/admin/articles')
}
