import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { createTestDb, cleanDb } from '../../test/setup-db'
import type { PrismaClient } from '@prisma/client'
import {
  createManualArticleDb,
  updateArticleDb,
  togglePinDb,
  toggleFeatureDb,
  softDeleteDb,
  listArticlesAdmin,
} from './articles-actions'

let db: PrismaClient

beforeEach(async () => {
  db = await createTestDb()
  await cleanDb(db)
})

afterEach(async () => {
  await db.$disconnect()
})

// Helper: create a bezirk for testing
async function createBezirk(db: PrismaClient, slug: string, name: string) {
  return db.bezirk.create({
    data: { slug, name, gemeindeSynonyms: [] },
  })
}

describe('createManualArticle', () => {
  it('creates article with source=MANUAL, isAutoGenerated=false, status=PUBLISHED', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')

    const article = await createManualArticleDb(db, {
      title: 'Test Article',
      content: 'Test content',
      bezirkIds: [bezirk.id],
    })

    expect(article.source).toBe('MANUAL')
    expect(article.isAutoGenerated).toBe(false)
    expect(article.status).toBe('PUBLISHED')
    expect(article.publishedAt).not.toBeNull()
  })

  it('creates ArticleBezirk junction rows for each bezirkId', async () => {
    const bezirk1 = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const bezirk2 = await createBezirk(db, 'liezen', 'Liezen')

    const article = await createManualArticleDb(db, {
      title: 'Multi-Bezirk Article',
      content: 'Content',
      bezirkIds: [bezirk1.id, bezirk2.id],
    })

    const junctions = await db.articleBezirk.findMany({
      where: { articleId: article.id },
    })
    expect(junctions).toHaveLength(2)
    expect(junctions.map((j) => j.bezirkId).sort()).toEqual(
      [bezirk1.id, bezirk2.id].sort()
    )
  })

  it('sets isPinned and isFeatured from input', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')

    const article = await createManualArticleDb(db, {
      title: 'Pinned Article',
      content: 'Content',
      bezirkIds: [bezirk.id],
      isPinned: true,
      isFeatured: true,
    })

    expect(article.isPinned).toBe(true)
    expect(article.isFeatured).toBe(true)
  })
})

describe('updateArticle', () => {
  it('updates title, content, seoTitle, metaDescription on any article', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const created = await createManualArticleDb(db, {
      title: 'Original Title',
      content: 'Original content',
      bezirkIds: [bezirk.id],
    })

    await updateArticleDb(db, {
      id: created.id,
      title: 'Updated Title',
      content: 'Updated content',
      seoTitle: 'SEO Title',
      metaDescription: 'Meta description',
    })

    const updated = await db.article.findUnique({ where: { id: created.id } })
    expect(updated?.title).toBe('Updated Title')
    expect(updated?.content).toBe('Updated content')
    expect(updated?.seoTitle).toBe('SEO Title')
    expect(updated?.metaDescription).toBe('Meta description')
  })

  it('replaces ArticleBezirk assignments when bezirkIds provided', async () => {
    const bezirk1 = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const bezirk2 = await createBezirk(db, 'liezen', 'Liezen')
    const bezirk3 = await createBezirk(db, 'bruck', 'Bruck-Mürzzuschlag')

    const created = await createManualArticleDb(db, {
      title: 'Article',
      content: 'Content',
      bezirkIds: [bezirk1.id, bezirk2.id],
    })

    // Replace with new bezirkIds: remove bezirk2, add bezirk3
    await updateArticleDb(db, {
      id: created.id,
      bezirkIds: [bezirk1.id, bezirk3.id],
    })

    const junctions = await db.articleBezirk.findMany({
      where: { articleId: created.id },
    })
    expect(junctions).toHaveLength(2)
    const ids = junctions.map((j) => j.bezirkId).sort()
    expect(ids).toEqual([bezirk1.id, bezirk3.id].sort())
    // bezirk2 must be gone
    expect(ids).not.toContain(bezirk2.id)
  })
})

describe('togglePin', () => {
  it('flips isPinned on the target article', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const article = await createManualArticleDb(db, {
      title: 'Article',
      content: 'Content',
      bezirkIds: [bezirk.id],
      isPinned: false,
    })

    const after1 = await togglePinDb(db, article.id)
    expect(after1.isPinned).toBe(true)

    const after2 = await togglePinDb(db, article.id)
    expect(after2.isPinned).toBe(false)
  })
})

describe('toggleFeature', () => {
  it('flips isFeatured on the target article', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const article = await createManualArticleDb(db, {
      title: 'Article',
      content: 'Content',
      bezirkIds: [bezirk.id],
      isFeatured: false,
    })

    const after1 = await toggleFeatureDb(db, article.id)
    expect(after1.isFeatured).toBe(true)

    const after2 = await toggleFeatureDb(db, article.id)
    expect(after2.isFeatured).toBe(false)
  })
})

describe('softDelete', () => {
  it('sets status to REJECTED', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const article = await createManualArticleDb(db, {
      title: 'Article',
      content: 'Content',
      bezirkIds: [bezirk.id],
    })

    expect(article.status).toBe('PUBLISHED')

    await softDeleteDb(db, article.id)

    const deleted = await db.article.findUnique({ where: { id: article.id } })
    expect(deleted?.status).toBe('REJECTED')
  })
})

describe('listArticlesAdmin', () => {
  it('excludes REJECTED and FAILED articles by default', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    const published = await createManualArticleDb(db, {
      title: 'Published',
      content: 'Content',
      bezirkIds: [bezirk.id],
    })
    // Manually create a REJECTED article
    await db.article.create({
      data: {
        title: 'Rejected',
        content: 'Content',
        source: 'MANUAL',
        isAutoGenerated: false,
        status: 'REJECTED',
        publishedAt: new Date(),
      },
    })

    const results = await listArticlesAdmin(db)
    const statuses = results.map((a) => a.status)
    expect(statuses).toContain('PUBLISHED')
    expect(statuses).not.toContain('REJECTED')
  })

  it('includes bezirke relation', async () => {
    const bezirk = await createBezirk(db, 'graz', 'Graz (Stadt)')
    await createManualArticleDb(db, {
      title: 'Article',
      content: 'Content',
      bezirkIds: [bezirk.id],
    })

    const results = await listArticlesAdmin(db)
    expect(results[0]).toHaveProperty('bezirke')
    expect(results[0].bezirke).toHaveLength(1)
  })
})
