import { describe, it } from 'vitest'

describe('createManualArticle', () => {
  it.todo('creates article with source=MANUAL, isAutoGenerated=false, status=PUBLISHED')
  it.todo('creates ArticleBezirk junction rows for each bezirkId')
  it.todo('sets isPinned and isFeatured from input')
})

describe('updateArticle', () => {
  it.todo('updates title, content, seoTitle, metaDescription on any article')
  it.todo('replaces ArticleBezirk assignments when bezirkIds provided')
})

describe('togglePin', () => {
  it.todo('flips isPinned on the target article')
})

describe('toggleFeature', () => {
  it.todo('flips isFeatured on the target article')
})

describe('softDelete', () => {
  it.todo('sets status to REJECTED')
})
