import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { createTestDb, cleanDb } from '../../test/setup-db'
import type { PrismaClient } from '@prisma/client'
import {
  approveArticleDb,
  rejectArticleDb,
  listExceptionQueueDb,
} from './exceptions-actions'

let db: PrismaClient

beforeEach(async () => {
  db = await createTestDb()
  await cleanDb(db)
})

afterEach(async () => {
  await db.$disconnect()
})

// Helper: create a REVIEW-status article
async function createReviewArticle(db: PrismaClient, overrides?: object) {
  return db.article.create({
    data: {
      title: 'Review Article',
      content: 'Content',
      source: 'OTS_AT',
      isAutoGenerated: true,
      status: 'REVIEW',
      rawPayload: { original: 'payload' },
      publishedAt: null,
      ...overrides,
    },
  })
}

describe('approveArticle', () => {
  it('sets status to PUBLISHED', async () => {
    const article = await createReviewArticle(db)

    const approved = await approveArticleDb(db, article.id)

    expect(approved.status).toBe('PUBLISHED')
  })
})

describe('rejectArticle', () => {
  it('sets status to REJECTED', async () => {
    const article = await createReviewArticle(db)

    const rejected = await rejectArticleDb(db, article.id)

    expect(rejected.status).toBe('REJECTED')
  })
})

describe('listExceptionQueue', () => {
  it('returns only REVIEW-status articles', async () => {
    // Create one REVIEW and one PUBLISHED article
    await createReviewArticle(db, { title: 'Review Article' })
    await db.article.create({
      data: {
        title: 'Published Article',
        content: 'Content',
        source: 'OTS_AT',
        isAutoGenerated: true,
        status: 'PUBLISHED',
        publishedAt: new Date(),
      },
    })

    const queue = await listExceptionQueueDb(db)

    expect(queue).toHaveLength(1)
    expect(queue[0].status).toBe('REVIEW')
    expect(queue[0].title).toBe('Review Article')
  })

  it('includes rawPayload for side-by-side display', async () => {
    await createReviewArticle(db, { rawPayload: { headline: 'Original headline' } })

    const queue = await listExceptionQueueDb(db)

    expect(queue[0].rawPayload).toEqual({ headline: 'Original headline' })
  })
})
